### ISSUE TITLE
GraphQL error when trying to create an account 

### ISSUE THREAD

**Issue by clue4** [sandboxnu/ScoutTrek-Backend#5]
**Problem:** When trying to create an account, at the patrol selection part of the signin process, we get a GraphQL error that says _Troop.findOne(some params) query_ has already been executed. 
**Solution:** Identify and patch the bug so that we are able to select a patrol and actually create an account
**More description:** Due to signup flow, this prevents the completion of creating an account, since we are unable to continue. We are still able to go back in the signup process, but we cannot continue.

**Specs:**
- [x] Research bug -- when does it happen? What causes it? Can we trigger it on purpose or does it seem random? (etc)
- [x] Ensure that GraphQL error does not happen when trying to select a patrol
    - [ ] Ensure that after fixing this bug, the rest of the account creation process remains smooth / continues as expected (there might be more bugs related to this spec, in which case additional tickets will be created)

**Additional:** Ross noted that this might be related to combining async/await and callbacks. This might be one area to look into first -- ty for the info and hints Ross!

**Comment by KobeZ123** [comment]
Ross is the only one who uses android (can get android emulators later) -- this might also be something to look into

**Comment by clue4** [comment]
Closed by PR #4
